[package]
name = "exonum-swarm"
version = "0.1.0"
authors = ["louashka <louashka@yandex.ru>"]

[dependencies]
exonum = { version = "0.9.0", path = "../../exonum" }
failure = "0.1.2"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

[dev-dependencies]
exonum-testkit = { version = "0.9.0", path = "../../testkit" }
rand = "=0.4.2"
pretty_assertions = "=0.5.1"
assert_matches = "1.2.0"
